
---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  datasource.auto-config.enabled: false

---
spring:
  config.activate.on-profile: cloud
logging:
  level:
    root: INFO
    com.sap.cap.esmlsocustactionset.services.ServiceCloudV2API: INFO
    com.sap.cap.esmlsocustactionset.handlers.EsmLsoCaseChangeHandler: INFO